### PR TITLE
[API] Added `getParams` API at `governance` and `klay` namespaces

### PR DESCRIPTION
**Pull request by hyunsooda**
## Proposed changes

- Following updates for the newly added API `getParams` (See: https://github.com/klaytn/klaytn/pull/1783)
- Version update from `1.9.1` to `1.10.1` in `package-lock.json`.

Do not forget to update [caver-java](https://github.com/klaytn/caver-java) as well.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/caver-js/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/caver-js)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nohkwak** [comment]
@hyunsooda 
image

In the document above shared by @ian, it is written that both getItemAt and getParams should be supported in version 1.10.2.
Please, keep getItemAt supported until the next version and check CLA.

**Comment by nohkwak** [comment]
When I reviewed it again, I saw that both APIs are still supported, only the test cases are missing. Please ignore the comments above. Thank you.

**Comment by hyunsooda** [comment]
Added missing `klay` namespace in JS binding. Thanks.

**Review by nohkwak — APPROVED** [review]
LGTM

**Review by kjeom — APPROVED** [review]

**Pull request merged**
