### PR TITLE
Fix setProvider bug

### PR DESCRIPTION
**Pull request by Jongsic**
## Proposed changes

- Bug fix connection setProvider

## Types of changes

Please put an x in the boxes related to your change.

- [ x ] Bugfix

## Checklist

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/caver-js/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/caver-js)

## Description

before this change, Caver cannot any rpc requests after calling setProvider method.

### CODE REVIEW

**Comment by jimni1222** [comment]
Hi there :)
Thank you for your contribution to fix the bug in caver-js. But it looks like you haven't signed the CLA yet. 

I was able to find what was missing because of this PR, and I want to put this PR under the review process as soon as possible. :)

**Comment by Jongsic** [comment]
I have signed the CLA. but it didnt apply to this PR page yet.

and It's page says "You have signed the CLA for klaytn/caver-js" ( https://cla-assistant.io/klaytn/caver-js?pullRequest=90 )

Please check cla assistant.

**Comment by Jongsic** [comment]
And I think no more description need for this PR.
because this is trivial bugs. and can reproduce always just by calling setProvider of caver instance.

**Comment by jimni1222** [comment]
Please make sure that the email address you used to commit has been added to your Github account.

**Comment by kjhman21** [comment]
@Jongsic Please take a look:
https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by kjhman21** [comment]
@Jongsic 
It also would be good to add more description as you wrote in the comment:
>  can reproduce always just by calling setProvider of caver instance.

**Comment by Jongsic** [comment]
I added description of PR.

CLA did not accept my sign even i added email of this commit. (now i removed the email address again.)

**Comment by kjhman21** [comment]
@Jongsic 

Please check that
1. Enter your github settings by clicking your profile image at the top right corner.
2. Enter your email settings by clicking "Emails" in the left "Personal settings" menu.
3. Make sure that your "primary email" is "jongsic@ozys.net".

I found the email address "jongsic@ozys.net" from your commit.


Also, you can check that you set your primary email address correctly by checking your commit detail page.
https://github.com/klaytn/caver-js/pull/90/commits/ea870be979311f5de92bd0810e9193305e7aff83

You can find "Jongsic committed 2 days ago" in the commit message, but "Jongsic" is not clickable. If you set right, this should be clickable.

Sorry for the inconvenience.

**Comment by Jongsic** [comment]
I had added jongsic@ozys.net in my email list and made name of commit clickable when 6 days ago.  
but CLA did not accept my sign then.

and... today I added email again and tried signing again. but CLA don't work.
I think CLA has problem. and not email address problem

**Comment by kjhman21** [comment]
I just closed and reopened this PR.

Thanks for the effort. I will approve this soon.

**Comment by kjhman21** [comment]
@Jongsic Do you have permission of merging this PR? Then, please merge this.
If not, please leave a comment. I will do that for you. :)

**Comment by Jongsic** [comment]
Github says "You’re not authorized to merge this pull request."

**Comment by kjhman21** [comment]
Got it. I will do that for you. Thanks for your effort!

**Pull request merged**
