### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by frontalnh**
## Proposed changes

fix invalid types

## Types of changes

Please put an x in the boxes related to your change.

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/caver-js/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/caver-js)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jimni1222** [comment]
@frontalnh Hi, thank you for contribution! 
For some reason, Circle CI does not seem to work properly.
Could you add an empty commit to let Circle CI work?

**Review by jimni1222 — APPROVED** [review]
LGTM!

**Comment by frontalnh** [comment]
> @frontalnh Hi, thank you for contribution! For some reason, Circle CI does not seem to work properly. Could you add an empty commit to let Circle CI work?

okay i'll make empty commit!

**Comment by jimni1222** [comment]
@frontalnh Sorry for bothering you. I think there is something wrong with circle ci maybe... i will ask to devops team! Thanks

**Comment by iv0rish** [comment]
Hi @frontalnh, we've fixed CircleCI issue. Appreciate for your contribution :)

**Pull request merged**
