### PR TITLE
refactoring testcase of CAVERJS-UNIT-WALLET-396

### PR DESCRIPTION
**Pull request by skqksh**
## Proposed changes

- Refactored an testcase to easy to read

## Types of changes

- [ ] Bugfix
- [ ] New feature or enhancement
- [x] Others

## Checklist

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/caver-js/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/caver-js)
- [ ] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- N/A

## Further comments

- N/A

### CODE REVIEW

**Comment by skqksh** [comment]
@jimni1222 

I have some questions about the change 'Set nonce with pending tag' what you commited

1. You added 'pending' option to get tx count. in case of web3.js, they don't. why it's different from web3.js

2. Following 3 functions changed, but only 1 testcase added
I thinnk, it needs more testcases for the other functions.
- signTransaction
- feePayerSignTransaction
- getRawTransactionWithSignatures

Thanks

**Comment by jimni1222** [comment]
> @jimni1222
> 
> I have some questions about the change 'Set nonce with pending tag' what you commited
> 
> 1. You added 'pending' option to get tx count. in case of web3.js, they don't. why it's different from web3.js
> 2. Following 3 functions changed, but only 1 testcase added
>    I thinnk, it needs more testcases for the other functions.
> 
> * signTransaction
> * feePayerSignTransaction
> * getRawTransactionWithSignatures
> 
> Thanks

Hello, I will answer your question.

1. The reason we set nonce with the pending tag is that before a transaction which sent to the node is processed (if it still exists in the transaction pool), if user try to send another transaction it will fail because a transaction of the same nonce exists. We recognize that it is handled differently from web3.js, but it is decided after discussing that 'pending' tag can handle this case.

2. Yes, I realize that test code is needed for other functions. I will add test code for other functions later. Thank you for the reminder :)

**Comment by jimni1222** [comment]
> @jimni1222
> 
> I have some questions about the change 'Set nonce with pending tag' what you commited
> 
> 1. You added 'pending' option to get tx count. in case of web3.js, they don't. why it's different from web3.js
> 2. Following 3 functions changed, but only 1 testcase added
>    I thinnk, it needs more testcases for the other functions.
> 
> * signTransaction
> * feePayerSignTransaction
> * getRawTransactionWithSignatures
> 
> Thanks

I added test codes in #186 . Please feel free to any comments !!! :) Thank you!

**Comment by skqksh** [comment]
> > @jimni1222
> > I have some questions about the change 'Set nonce with pending tag' what you commited
> > 
> > 1. You added 'pending' option to get tx count. in case of web3.js, they don't. why it's different from web3.js
> > 2. Following 3 functions changed, but only 1 testcase added
> >    I thinnk, it needs more testcases for the other functions.
> > 
> > 
> > * signTransaction
> > * feePayerSignTransaction
> > * getRawTransactionWithSignatures
> > 
> > Thanks
> 
> I added test codes in #186 . Please feel free to any comments !!! :) Thank you!

Thanks for tagging me. 
I suggest you some ideas
1. caver-js are already using assertion library, chai. so no reason not use assert of chai
    ```Javascript
    // before
    const assert = require('assert')
    const { expect } = require('./extendedChai')
    
     //after
    const { expect, assert } = require('./extendedChai')
    ```
    - you can compare methods with following docs
        - [nodejs.org](https://nodejs.org/api/assert.html)
        - [www.chaijs.com](https://www.chaijs.com/api/assert/)
        - [My blog](https://blog.naver.com/skqksh/221741262886)
1. How about remove 'no-unused-vars' option in .eslintrc.js
    - Actually, setNonceWithPendingTag.js file don't need 'assert' , but it has.
    - You can check unused variables out easily with just remove option

**Pull request merged**
