### PR TITLE
Update to support typescript

### PR DESCRIPTION
**Pull request by skqksh**
## Proposed changes

- Support Typescript (#157)

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/caver-js/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/caver-js)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- #157

## Further comments

I added declare files to support typescript. I focused to change files where are in [official docs](https://docs.klaytn.com/bapp/sdk/caver-js)
Lots of testcases include unnecessary options(parameters, etc) for the test, so I hope to change *.js files to *.ts
I believe that It will help to find bugs or prevent other type errors

### CODE REVIEW

**Comment by jimni1222** [comment]
@skqksh Can you check circle CI error?

**Comment by skqksh** [comment]
@jimni1222 
I'll try to find why there is 
Cannot find module 'ts-node/register' 
error in circleci, even there is 'ts-node' in package.json

**Comment by skqksh** [comment]
@jimni1222 
I don't know why circleci can't find ts-node. maybe config.yml setting, I guess...
So, I reverted .ts testcase files to .js not to use ts-node

**Comment by jimni1222** [comment]
@skqksh Can you try to install ts-node globally?

**Comment by skqksh** [comment]
I tried yesterday, but it didn't work

2020년 11월 10일 (화) 07:58, Jasmine <notifications@github.com>님이 작성:

**Comment by jimni1222** [comment]
@skqksh 

Please refer to this commit https://github.com/klaytn/caver-js/pull/390/commits/7e03ac5809d2b848aed4478ababe700493f53cdc

**Pull request closed without merging**
