### PR TITLE
[Master] release/v1.5.0 QA Sign-off

### PR DESCRIPTION
**Pull request by circleci-klaytn**
This PR is automatically created by CI to release a new official version of caver-js.

When this PR is approved by QA team, a new version will be released.

### CODE REVIEW

**Comment by jimni1222** [comment]
### caver-js v1.5.0 QA Result

### Functional Test Result

1. UNIT-ACCOUNT
**Total Test Cases** 65 = PASS  65 + FAIL  0 + N/A  0
**Newly Added Test Cases** 65 = PASS 65 + FAIL 0 + N/A 0

2. UNIT-KEYRING
**Total Test Cases** 165 = PASS  134 + FAIL  0 + N/A  31
**Newly Added Test Cases** 165 = PASS 134 + FAIL 0 + N/A 31

3. UNIT-KEYRINGCONTAINER
**Total Test Cases** 51 = PASS  49 + FAIL  0 + N/A  2
**Newly Added Test Cases** 51 = PASS 49 + FAIL 0 + N/A 2

4. UNIT-TRANSACTION
**Total Test Cases** 390 = PASS  365 + FAIL  0 + N/A  25
**Newly Added Test Cases** 390 = PASS 365 + FAIL 0 + N/A 25

5. UNIT-TRANSACTIONFD
**Total Test Cases** 513 = PASS  491 + FAIL  0 + N/A  22
**Newly Added Test Cases** 513 = PASS 491 + FAIL 0 + N/A 22

6. UNIT-TRANSACTIONFDR
**Total Test Cases** 520 = PASS  498 + FAIL  0 + N/A  22
**Newly Added Test Cases** 520 = PASS 498 + FAIL 0 + N/A 22

7. UNIT-RPC
**Total Test Cases** 5 = PASS  5 + FAIL  0 + N/A  0
**Newly Added Test Cases** 5 = PASS 5 + FAIL 0 + N/A 0

8. UNIT-KCT 
(This test case has been changed to test using the newly introduced caver.kct.kip7/caver.kct.kip17 from the existing test case.)           
**Total Test Cases** 159 = PASS  151 + FAIL  0 + N/A  8
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
9. UNIT-SER          
**Total Test Cases** 67 = PASS  65 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
10. UNIT-TX              
**Total Test Cases** 730 = PASS  641 + FAIL  0 + N/A  89
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
11. UNIT-WALLET   
**Total Test Cases** 430 = PASS  404 + FAIL  0 + N/A  26
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0

12. UNIT-ETC           
**Total Test Cases** 249 = PASS  240 + FAIL  0 + N/A  9
**Newly Added Test Cases** 46 = PASS 45 + FAIL 0 + N/A 1 

### Integration Test Result

1. INT-LEGACY     
**Total Test Cases** 19 = PASS  17 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

2. INT-ACCUP      
**Total Test Cases** 48  = PASS  40 + FAIL  0 + N/A  8
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

3. INT-VT              
**Total Test Cases** 13 = PASS  13 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

4. INT-VTM           
**Total Test Cases** 16 = PASS  16 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

5. INT-EXE            
**Total Test Cases** 14 = PASS  14 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

6. INT-DEPL         
**Total Test Cases** 23 = PASS  16 + FAIL  0 + N/A  7
**Newly Added Test Cases**0 = PASS 0 + FAIL 0 + N/A 0

7. INT-CANCEL     
**Total Test Cases** 7 = PASS  7 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

8. INT-FD              
**Total Test Cases** 44 = PASS  44 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

9. INT-FDR            
**Total Test Cases** 62 = PASS  62 + FAIL  0 + N/A  0 
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

10. INT-SIGVALI   
**Total Test Cases** 18 = PASS  15 + FAIL  0 + N/A  3
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

11. INT-API             
**Total Test Cases** 52 = PASS  46 + FAIL  0 + N/A  6
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

12. INT-SOL           
**Total Test Cases** 131 = PASS  129 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0

**Comment by jimni1222** [comment]
### caver-js v1.5.0 QA Result

### Functional Test Result

1. UNIT-ACCOUNT
**Total Test Cases** 65 = PASS  65 + FAIL  0 + N/A  0
**Newly Added Test Cases** 65 = PASS 65 + FAIL 0 + N/A 0

2. UNIT-KEYRING
**Total Test Cases** 165 = PASS  134 + FAIL  0 + N/A  31
**Newly Added Test Cases** 165 = PASS 134 + FAIL 0 + N/A 31

3. UNIT-KEYRINGCONTAINER
**Total Test Cases** 51 = PASS  49 + FAIL  0 + N/A  2
**Newly Added Test Cases** 51 = PASS 49 + FAIL 0 + N/A 2

4. UNIT-TRANSACTION
**Total Test Cases** 390 = PASS  365 + FAIL  0 + N/A  25
**Newly Added Test Cases** 390 = PASS 365 + FAIL 0 + N/A 25

5. UNIT-TRANSACTIONFD
**Total Test Cases** 513 = PASS  491 + FAIL  0 + N/A  22
**Newly Added Test Cases** 513 = PASS 491 + FAIL 0 + N/A 22

6. UNIT-TRANSACTIONFDR
**Total Test Cases** 520 = PASS  498 + FAIL  0 + N/A  22
**Newly Added Test Cases** 520 = PASS 498 + FAIL 0 + N/A 22

7. UNIT-RPC
**Total Test Cases** 5 = PASS  5 + FAIL  0 + N/A  0
**Newly Added Test Cases** 5 = PASS 5 + FAIL 0 + N/A 0

8. UNIT-KCT 
(This test case has been changed to test using the newly introduced caver.kct.kip7/caver.kct.kip17 from the existing test case.)           
**Total Test Cases** 159 = PASS  151 + FAIL  0 + N/A  8
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
9. UNIT-SER          
**Total Test Cases** 67 = PASS  65 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
10. UNIT-TX              
**Total Test Cases** 730 = PASS  641 + FAIL  0 + N/A  89
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
11. UNIT-WALLET   
**Total Test Cases** 430 = PASS  404 + FAIL  0 + N/A  26
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0

12. UNIT-ETC           
**Total Test Cases** 249 = PASS  240 + FAIL  0 + N/A  9
**Newly Added Test Cases** 46 = PASS 45 + FAIL 0 + N/A 1 

### Integration Test Result

1. INT-LEGACY     
**Total Test Cases** 19 = PASS  17 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

2. INT-ACCUP      
**Total Test Cases** 48  = PASS  40 + FAIL  0 + N/A  8
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

3. INT-VT              
**Total Test Cases** 13 = PASS  13 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

4. INT-VTM           
**Total Test Cases** 16 = PASS  16 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

5. INT-EXE            
**Total Test Cases** 14 = PASS  14 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

6. INT-DEPL         
**Total Test Cases** 23 = PASS  16 + FAIL  0 + N/A  7
**Newly Added Test Cases**0 = PASS 0 + FAIL 0 + N/A 0

7. INT-CANCEL     
**Total Test Cases** 7 = PASS  7 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

8. INT-FD              
**Total Test Cases** 44 = PASS  44 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

9. INT-FDR            
**Total Test Cases** 62 = PASS  62 + FAIL  0 + N/A  0 
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

10. INT-SIGVALI   
**Total Test Cases** 18 = PASS  15 + FAIL  0 + N/A  3
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

11. INT-API             
**Total Test Cases** 52 = PASS  46 + FAIL  0 + N/A  6
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

12. INT-SOL           
**Total Test Cases** 131 = PASS  129 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0

**Comment by jimni1222** [comment]
### caver-js v1.5.0 QA Result

### Functional Test Result

1. UNIT-ACCOUNT
**Total Test Cases** 65 = PASS  65 + FAIL  0 + N/A  0
**Newly Added Test Cases** 65 = PASS 65 + FAIL 0 + N/A 0

2. UNIT-KEYRING
**Total Test Cases** 165 = PASS  134 + FAIL  0 + N/A  31
**Newly Added Test Cases** 165 = PASS 134 + FAIL 0 + N/A 31

3. UNIT-KEYRINGCONTAINER
**Total Test Cases** 51 = PASS  49 + FAIL  0 + N/A  2
**Newly Added Test Cases** 51 = PASS 49 + FAIL 0 + N/A 2

4. UNIT-TRANSACTION
**Total Test Cases** 390 = PASS  365 + FAIL  0 + N/A  25
**Newly Added Test Cases** 390 = PASS 365 + FAIL 0 + N/A 25

5. UNIT-TRANSACTIONFD
**Total Test Cases** 513 = PASS  491 + FAIL  0 + N/A  22
**Newly Added Test Cases** 513 = PASS 491 + FAIL 0 + N/A 22

6. UNIT-TRANSACTIONFDR
**Total Test Cases** 520 = PASS  498 + FAIL  0 + N/A  22
**Newly Added Test Cases** 520 = PASS 498 + FAIL 0 + N/A 22

7. UNIT-RPC
**Total Test Cases** 5 = PASS  5 + FAIL  0 + N/A  0
**Newly Added Test Cases** 5 = PASS 5 + FAIL 0 + N/A 0

8. UNIT-KCT 
(This test case has been changed to test using the newly introduced caver.kct.kip7/caver.kct.kip17 from the existing test case.)           
**Total Test Cases** 159 = PASS  151 + FAIL  0 + N/A  8
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
9. UNIT-SER          
**Total Test Cases** 67 = PASS  65 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
10. UNIT-TX              
**Total Test Cases** 730 = PASS  641 + FAIL  0 + N/A  89
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 
11. UNIT-WALLET   
**Total Test Cases** 430 = PASS  404 + FAIL  0 + N/A  26
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0

12. UNIT-ETC           
**Total Test Cases** 250 = PASS  241 + FAIL  0 + N/A  9
**Newly Added Test Cases** 47 = PASS 46 + FAIL 0 + N/A 1 

### Integration Test Result

1. INT-LEGACY     
**Total Test Cases** 19 = PASS  17 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

2. INT-ACCUP      
**Total Test Cases** 48  = PASS  40 + FAIL  0 + N/A  8
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

3. INT-VT              
**Total Test Cases** 13 = PASS  13 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

4. INT-VTM           
**Total Test Cases** 16 = PASS  16 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

5. INT-EXE            
**Total Test Cases** 14 = PASS  14 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

6. INT-DEPL         
**Total Test Cases** 23 = PASS  16 + FAIL  0 + N/A  7
**Newly Added Test Cases**0 = PASS 0 + FAIL 0 + N/A 0

7. INT-CANCEL     
**Total Test Cases** 7 = PASS  7 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

8. INT-FD              
**Total Test Cases** 44 = PASS  44 + FAIL  0 + N/A  0
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

9. INT-FDR            
**Total Test Cases** 62 = PASS  62 + FAIL  0 + N/A  0 
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

10. INT-SIGVALI   
**Total Test Cases** 18 = PASS  15 + FAIL  0 + N/A  3
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

11. INT-API             
**Total Test Cases** 52 = PASS  46 + FAIL  0 + N/A  6
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0 

12. INT-SOL           
**Total Test Cases** 131 = PASS  129 + FAIL  0 + N/A  2
**Newly Added Test Cases** 0 = PASS 0 + FAIL 0 + N/A 0

**Comment by jimni1222** [comment]
The `v1.5.0-rc.4` release contains only README.md file modifications, so there are no changes to the code and tests.

**Comment by kjhman21** [comment]
@jimni1222 근데, 지나고보니, (This test case has been changed to test using the newly introduced caver.kct.kip7/caver.kct.kip17 from the existing test case.)  요렇게 하시면 기존 코드들은 테스트가 안되는건가요?

**Comment by jimni1222** [comment]
기존 테스트 케이스마다 caver.klay.KIP7이랑 caver.kct.kip7 이렇게 사용하여 2번씩 동작하게 변경되었습니다.

2020년 6월 25일 (목) 오전 7:49, Junghyun Colin Kim <notifications@github.com>님이
작성:

**Comment by kjhman21** [comment]
@jimni1222 넵 알겠습니다. 감사합니다. :)

**Pull request merged**
